CREATE TABLE jamfinder_bands (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  band_name TEXT NOT NULL UNIQUE,
  genre TEXT NOT NULL,
  location TEXT NOT NULL,
  description TEXT,
  members INTEGER [],
  new_members BOOLEAN NOT NULL DEFAULT FALSE,
  bandleader INTEGER REFERENCES jamfinder_users(id) ON DELETE CASCADE
);