CREATE TABLE jamfinder_band_messages (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  band INTEGER REFERENCES jamfinder_bands(id) ON DELETE CASCADE NOT NULL,
  author INTEGER REFERENCES jamfinder_users(id) ON DELETE CASCADE NOT NULL,
  author_user_name TEXT REFERENCES jamfinder_users(user_name) ON DELETE CASCADE NOT NULL,
  date_published TIMESTAMP NOT NULL,
  message TEXT NOT NULL
);